### ISSUE TITLE
一部分图标包不支持，且导致桌面明显卡顿

### ISSUE THREAD

**Issue by ForbAvalon** [manhong2112/MimikkoUi-Mod#2]
很喜欢这个插件，不过我的桌面因此卡死几回，开机第一次启动桌面会持续很久的加载，希望优化一下

**Comment by paletteOvO** [comment]
我不肯定啟動時間長是不是模塊的問題, 畢竟啟動時我並沒做太多東西, 有空我測試下..
卡死時具體是在哪個頁面呢? 還有是做了甚麼才卡死的?
另外就是不支持的圖標包是哪些?

**Comment by ForbAvalon** [comment]
酷安上的meeye图标应用无效，反而会让桌面卡顿。每次开机，到桌面图标正常显示都有超过1分钟的加载时间。更换壁纸会导致mimikko卡住变成两个，一个不会动，另一个正常反应，重新进入插件并回到桌面可以解决。

2018年4月1日 上午11:12，manhong2112 <notifications@github.com>写道：

我不肯定啟動時間長是不是模塊的問題, 畢竟啟動時我並沒做太多東西, 有空我測試下..
卡死時具體是在哪個頁面呢? 還有是做了甚麼才卡死的?
另外就是不支持的圖標包是哪些?

**Comment by paletteOvO** [comment]
em..我看了一下, 讀取圖標時出了一堆錯誤信息, 我懷疑卡死就是因為這個, 你試試其他圖標包(比如delta, 至少我手機上是能用的)看看還會不會卡死?

**Comment by paletteOvO** [comment]
....我反編譯了一下meeye, 這大概不是我的鍋, 作者把ComponentInfo{com.MobileTicket/com.alipay.mobile.quinox.LauncherActivity}的屬性drawable打成了drawavle, 導致讀取時出錯了, 我之後會加個檢查的, 你要不跟圖標包作者回報一下?

**Comment by ForbAvalon** [comment]
我更换使用pure不会出现此问题，所以我现在在用pure。

2018年4月1日 上午11:48，manhong2112 <notifications@github.com>写道：

em..我看了一下, 讀取圖標時出了一堆錯誤信息, 我懷疑卡死就是因為這個, 你試試其他圖標包(比如delta, 至少我手機上是能用的)看看還會不會卡死?

**Comment by ForbAvalon** [comment]
ok，我会注上你的名字的

2018年4月1日 下午12:04，manhong2112 <notifications@github.com>写道：

....我反編譯了一下meeye, 這大概不是我的鍋, 作者把ComponentInfo{com.MobileTicket/com.alipay.mobile.quinox.LauncherActivity}的屬性drawable打成了drawavle, 導致讀取時出錯了, 我之後會加個檢查的, 你要不跟圖標包作者回報一下?

**Comment by ForbAvalon** [comment]
原来你有酷安的账号，那你自己报吧，谢谢你的耐心回答！！

2018年4月1日 下午12:25，Leonhardt Avalon <gridamasleo@outlook.com>写道：
ok，我会注上你的名字的

2018年4月1日 下午12:04，manhong2112 <notifications@github.com>写道：

....我反編譯了一下meeye, 這大概不是我的鍋, 作者把ComponentInfo{com.MobileTicket/com.alipay.mobile.quinox.LauncherActivity}的屬性drawable打成了drawavle, 導致讀取時出錯了, 我之後會加個檢查的, 你要不跟圖標包作者回報一下?

**Comment by paletteOvO** [comment]
em..我是有, 但懶得去弄實名, 所以目前是說不了話的(攤手
