### ISSUE TITLE
切換桌面時抽屜背景會消失

### ISSUE THREAD

**Issue by paletteOvO** [manhong2112/MimikkoUi-Mod#3]
推測是因為系統主題依照桌面背景自動更新然後導致一些鬼知道是甚麼回事的問題, 沒有logcat
(也不能說沒有, 有一個leaked IntentReceiver, 但感覺不關我事, 嗯...)

因為夢夢奈有提供自動改背景的功能..雖然不知道有多少人用, 但總得修的, 嗯....

**Comment by ForbAvalon** [comment]
梦梦奈的背景不是调用系统的吗？她自带的壁纸库有自己的API？

**Comment by paletteOvO** [comment]
@ForbAvalon 是系統背景沒錯，但更換背景會導致系統主題顏色更新，然後不造發生了甚麼導致模組載入了兩次（嚴格說是夢夢奈的onCreate執行了兩次）然後背景掛掉了...我覺得應該不會太多人有這個bug，畢竟用主題的人也不多

**Comment by ForbAvalon** [comment]
明白了，话说你有打算在酷安上架吗？那边很多人都盼望有图标包功能。

2018年4月8日 14:52，manhong2112 <notifications@github.com>写道：

@ForbAvalon<https://github.com/ForbAvalon> 是系統背景沒錯，但更換背景會導致系統主題顏色更新，然後不造發生了甚麼導致模組載入了兩次（嚴格說是夢夢奈的onCreate執行了兩次）然後背景掛掉了。。我覺得應該不會太多人有這個bug，畢竟用主題的人也不多

**Comment by paletteOvO** [comment]
@ForbAvalon 暫時沒有，一來沒空，二來排斥實名驗證，三來我對酷安實在不太感冒。。
等等看有多少人用吧。。多人用的話我有空弄一下

**Comment by paletteOvO** [comment]
1.9自帶了
