### ISSUE TITLE
个别图标包无法应用

### ISSUE THREAD

**Issue by ForbAvalon** [manhong2112/MimikkoUi-Mod#6]
一个叫做Sony xzp的图标包无法使用，即使拖到最上端有没有成功应用。

**Comment by ForbAvalon** [comment]
Pure图标包

**Comment by paletteOvO** [comment]
Sony xzp是手機吧, 不能用的話有logcat嗎, 總之我先去下個pure看看...

**Comment by paletteOvO** [comment]
唔, pure還挺好看的
我這邊是能用的, 所以大概得等logcat了
順便以防萬一我說一下, 我下的是me.morirain.dev.iconpack.pure

**Comment by ForbAvalon** [comment]
OK，这个也只有一个人报了这个bug，其他人都没有问题。我觉得是他的手机系统问题。抱歉过了这么久才回复，我最近把Gmail的通知关了...

**Comment by paletteOvO** [comment]
唔，我覺得沒必要這麼快關啦，要是他能提供一下Log的話說不定我能修一下...
